#!/usr/bin/env sh
# Sets the background. If given an argument, will set file as background.

#background=$(gsettings get org.gnome.desktop.background picture-uri | cut -d"/" -f4-9 | tr -d "'")

[ ! -z "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Wallpaper changed."
xwallpaper --zoom ~/.config/wall.png
$HOME/.config/polybar/scripts/pywal.sh ~/.config/wall.png